#!/usr/bin/env bash
# Generate the shared secret coturn and Prosody both need to agree on for
# time-limited TURN credentials (RFC 5766-adjacent shared-secret mechanism —
# Prosody mints short-lived per-session username/password pairs against this
# secret via `external_service_secret`, coturn validates them against the
# SAME secret via `--static-auth-secret`; see docker-compose.override.yml's
# own coturn service comment for the fuller account). One secret, two
# consumers — this script is what keeps them from drifting apart, the same
# role generate-dev-cert.sh plays for the TLS cert/trust-anchor pair.
#
# LOCAL DEV/TEST ONLY, same status as the rest of this directory. Called by
# setup.sh; safe to run standalone too.
set -euo pipefail
cd "$(dirname "${BASH_SOURCE[0]}")/.jitsi-docker"

if [ ! -f .env ]; then
  echo ".jitsi-docker/.env not found — run setup.sh first." >&2
  exit 2
fi

if grep -q '^TURN_CREDENTIALS=' .env; then
  echo "TURN_CREDENTIALS already set in .jitsi-docker/.env — not rotating it."
  echo "(coturn and Prosody would disagree if only one side changed. Delete the line by hand first if you really want a new one, then re-run this script.)"
  exit 0
fi

SECRET=$(openssl rand -hex 32)
{
  echo ""
  echo "# --- TURN shared secret, generated by ../gen-turn-secret.sh ---"
  echo "TURN_CREDENTIALS=${SECRET}"
} >> .env

echo "TURN_CREDENTIALS generated and appended to .jitsi-docker/.env."
echo "Still needed before TURN actually works: uncomment and set TURN_HOST"
echo "in .jitsi-docker/.env to this machine's real LAN IP (same value as"
echo "JVB_ADVERTISE_IPS/PUBLIC_URL) — see olive.env's own comment on TURN_HOST."
